// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VidekVideoAPI.Models;

namespace VidekVideoAPI.Migrations
{
    [DbContext(typeof(VidekVideoAPIContext))]
    [Migration("20190826133316_foreignkeysadded")]
    partial class foreignkeysadded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VidekVideoAPI.Models.Thumbnail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SourcePath");

                    b.Property<int>("VideoID");

                    b.HasKey("Id");

                    b.HasIndex("VideoID");

                    b.ToTable("Thumbnails");
                });

            modelBuilder.Entity("VidekVideoAPI.Models.ThumbnailViewItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ThumbnailURL");

                    b.Property<string>("Title");

                    b.Property<int>("VideoId");

                    b.Property<string>("VideoURL");

                    b.HasKey("Id");

                    b.HasIndex("VideoId");

                    b.ToTable("ThumbnailViewItem");
                });

            modelBuilder.Entity("VidekVideoAPI.Models.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descirption");

                    b.Property<string>("SourcePath");

                    b.Property<string>("StreamURL");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Video");
                });

            modelBuilder.Entity("VidekVideoAPI.Models.Thumbnail", b =>
                {
                    b.HasOne("VidekVideoAPI.Models.Video", "Video")
                        .WithMany()
                        .HasForeignKey("VideoID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("VidekVideoAPI.Models.ThumbnailViewItem", b =>
                {
                    b.HasOne("VidekVideoAPI.Models.Video", "Video")
                        .WithMany()
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
